// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for DeploymentStatus.
const (
	Failed    DeploymentStatus = "failed"
	Pending   DeploymentStatus = "pending"
	Running   DeploymentStatus = "running"
	Succeeded DeploymentStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the DeploymentStatus enum.
func (e DeploymentStatus) Valid() bool {
	switch e {
	case Failed:
		return true
	case Pending:
		return true
	case Running:
		return true
	case Succeeded:
		return true
	default:
		return false
	}
}

// AuthRequest defines model for AuthRequest.
type AuthRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	ExpiresIn *int    `json:"expires_in,omitempty"`
	Token     *string `json:"token,omitempty"`
}

// CreateDeploymentRequest defines model for CreateDeploymentRequest.
type CreateDeploymentRequest struct {
	Config  *map[string]interface{} `json:"config,omitempty"`
	Name    string                  `json:"name"`
	Version string                  `json:"version"`
}

// Deployment defines model for Deployment.
type Deployment struct {
	CreatedAt *time.Time        `json:"created_at,omitempty"`
	Id        *string           `json:"id,omitempty"`
	Name      *string           `json:"name,omitempty"`
	Status    *DeploymentStatus `json:"status,omitempty"`
	Version   *string           `json:"version,omitempty"`
}

// DeploymentStatus defines model for Deployment.Status.
type DeploymentStatus string

// DeploymentList defines model for DeploymentList.
type DeploymentList struct {
	Items *[]Deployment `json:"items,omitempty"`
	Total *int          `json:"total,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code    *int    `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status        *string  `json:"status,omitempty"`
	UptimeSeconds *float64 `json:"uptime_seconds,omitempty"`
}

// GetDeploymentsParams defines parameters for GetDeployments.
type GetDeploymentsParams struct {
	Page     *int `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = AuthRequest

// PostDeploymentsJSONRequestBody defines body for PostDeployments for application/json ContentType.
type PostDeploymentsJSONRequestBody = CreateDeploymentRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login and receive a token
	// (POST /auth/login)
	PostAuthLogin(c *gin.Context)
	// List deployments
	// (GET /deployments)
	GetDeployments(c *gin.Context, params GetDeploymentsParams)
	// Create a deployment
	// (POST /deployments)
	PostDeployments(c *gin.Context)
	// Delete a deployment
	// (DELETE /deployments/{id})
	DeleteDeploymentsId(c *gin.Context, id string)
	// Get a deployment by id
	// (GET /deployments/{id})
	GetDeploymentsId(c *gin.Context, id string)
	// Service health
	// (GET /health)
	GetHealth(c *gin.Context)
	// Prometheus metrics endpoint (text/plain)
	// (GET /metrics)
	GetMetrics(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAuthLogin(c)
}

// GetDeployments operation middleware
func (siw *ServerInterfaceWrapper) GetDeployments(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDeploymentsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", c.Request.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDeployments(c, params)
}

// PostDeployments operation middleware
func (siw *ServerInterfaceWrapper) PostDeployments(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostDeployments(c)
}

// DeleteDeploymentsId operation middleware
func (siw *ServerInterfaceWrapper) DeleteDeploymentsId(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteDeploymentsId(c, id)
}

// GetDeploymentsId operation middleware
func (siw *ServerInterfaceWrapper) GetDeploymentsId(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDeploymentsId(c, id)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// GetMetrics operation middleware
func (siw *ServerInterfaceWrapper) GetMetrics(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMetrics(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/auth/login", wrapper.PostAuthLogin)
	router.GET(options.BaseURL+"/deployments", wrapper.GetDeployments)
	router.POST(options.BaseURL+"/deployments", wrapper.PostDeployments)
	router.DELETE(options.BaseURL+"/deployments/:id", wrapper.DeleteDeploymentsId)
	router.GET(options.BaseURL+"/deployments/:id", wrapper.GetDeploymentsId)
	router.GET(options.BaseURL+"/health", wrapper.GetHealth)
	router.GET(options.BaseURL+"/metrics", wrapper.GetMetrics)
}
