// Package model provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package model

import (
	"time"
)

// Defines values for DeploymentStatus.
const (
	Failed    DeploymentStatus = "failed"
	Pending   DeploymentStatus = "pending"
	Running   DeploymentStatus = "running"
	Succeeded DeploymentStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the DeploymentStatus enum.
func (e DeploymentStatus) Valid() bool {
	switch e {
	case Failed:
		return true
	case Pending:
		return true
	case Running:
		return true
	case Succeeded:
		return true
	default:
		return false
	}
}

// AuthRequest defines model for AuthRequest.
type AuthRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	ExpiresIn *int    `json:"expires_in,omitempty"`
	Token     *string `json:"token,omitempty"`
}

// CreateDeploymentRequest defines model for CreateDeploymentRequest.
type CreateDeploymentRequest struct {
	Config  *map[string]interface{} `json:"config,omitempty"`
	Name    string                  `json:"name"`
	Version string                  `json:"version"`
}

// Deployment defines model for Deployment.
type Deployment struct {
	CreatedAt *time.Time        `json:"created_at,omitempty"`
	Id        *string           `json:"id,omitempty"`
	Name      *string           `json:"name,omitempty"`
	Status    *DeploymentStatus `json:"status,omitempty"`
	Version   *string           `json:"version,omitempty"`
}

// DeploymentStatus defines model for Deployment.Status.
type DeploymentStatus string

// DeploymentList defines model for DeploymentList.
type DeploymentList struct {
	Items *[]Deployment `json:"items,omitempty"`
	Total *int          `json:"total,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code    *int    `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status        *string  `json:"status,omitempty"`
	UptimeSeconds *float64 `json:"uptime_seconds,omitempty"`
}

// GetDeploymentsParams defines parameters for GetDeployments.
type GetDeploymentsParams struct {
	Page     *int `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = AuthRequest

// PostDeploymentsJSONRequestBody defines body for PostDeployments for application/json ContentType.
type PostDeploymentsJSONRequestBody = CreateDeploymentRequest
